### ISSUE TITLE
Extracting PDFs from page content is not working properly

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3meilisearch#1]
It looks like there is a problem with the following regex from `IndexService`:

```
// Extract links to PDFs in fileadmin to parse
preg_match('/\/fileadmin(.*)\.pdf/s', $tsfe->content, $links);
```

The `$links` variable looks like the following when there is one document inside of the content:

```
array(2) {
  [0]=>
  string(83) "/fileadmin/user_upload/name-of-the-document.pdf"
  [1]=>
  string(69) "/user_upload/name-of-the-document"
}
```

The `$links` variable looks even weirder once there are multiple documents inside of the content.

**Comment by runepiper** [comment]
Should work as expected now.

**Comment by malteriechmann** [comment]
Sorry, but I still get weird output for `$links`.

```
array(2) {
  [0]=>
  array(1) {
    [0]=>
    string(338) "/fileadmin/user_upload/file-1">File 1</a> lorem ipsum <a href="/fileadmin/user_upload/file-2.pdf"
  }
  [1]=>
  array(1) {
    [0]=>
    string(324) "/user_upload/file-1">File 1</a> lorem ipsum <a href="/fileadmin/user_upload/file-2"
  }
}
```

**Comment by runepiper** [comment]
Sorry, cannot confirm this with my local up-to-date setup. Have you cleared the cache?

**Comment by malteriechmann** [comment]
Yes. Maybe let us have a direct chat.

**Comment by malteriechmann** [comment]
Thanks again. Working smoothly now.
