### ISSUE TITLE
Add some commands to interact search index

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3meilisearch#3]
I am not 100 % sure about this, but maybe we should add some TYPO3 commands to interact with the search index.

Some ideas:
- Remove pages index
- Remove specific page/pdf from pages index

If we agree against this, we should alternatively add the corresponding cURL commands inside of the README.

**Comment by runepiper** [comment]
Added: https://github.com/visuellverstehen/t3meilisearch/blob/5a50cd5/README.md#dropping-the-index

**Comment by malteriechmann** [comment]
Should be enough.
