### ISSUE TITLE
Remove query parameters and fragment from indexed URLs

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3meilisearch#5]
Right now all possible URLs get indexed. We should index only URLs without query parameters and without fragments.

Here are some example URLs:
- https://www.example.com/path
- https://www.example.com/path/
- https://www.example.com/path/?tx_extension[action]=show&tx_extension[article]=42&cHash=d41d8cd98f00b204e9800998ecf8427e
- https://www.example.com/path/#main-section
- https://www.example.com/path/#c42

For all of the URLs above only one URL should get indexed:
- https://www.example.com/path

**Comment by runepiper** [comment]
Should be fixed now. Just drop the index and the new index should only contain documents with clean urls.

**Comment by malteriechmann** [comment]
Just tested it. Works nicely. 👏
