### ISSUE TITLE
Only index URLs without trailing slash

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3meilisearch#7]
Right now some URLs get indexed twice (with and without trailing slash). We should index only URLs without trailing slash.

Now:
- https://www.example.com/path
- https://www.example.com/path/

In the future:
- https://www.example.com/path

**Comment by runepiper** [comment]
Did a change that might solve this issue but I haven't tested it yet.

**Comment by runepiper** [comment]
Tested it locally. Looks good for me

**Comment by malteriechmann** [comment]
Inspired by you, I used a simpler approach. Fine for you?

**Comment by runepiper** [comment]
Didn't know about `rtrim`. Love it!
